import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => {
  const banner = {
    backgroundColor: "#000",
    position: "relative",
    color: "#fff",
  };

  const containerText = {
    background: "-webkit-linear-gradient(180deg,#ffd86f,#fc6262)",
    justifyContent: "space-between",
  };

  const text = {
    color: "#fff",
  };

  const buttonContainer = {
    textAlign: "center",
  };

  const textFocusIn = {
    "-webkit-animation":
      "$textFocusIn 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
    animation: "$textFocusIn 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
  };

  const containerTextMobile = {
    ...containerText,
    position: "absolute",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    bottom: 30,

    "-webkit-animation":
      "$slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both",
    animation:
      "$slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both",
  };

  return {
    bannerMobile: {
      ...banner,
      height: "80vh",
      zIndex: -1,
      padding: 60,
    },

    bannerDesktop: {
      ...banner,
      height: "100vh",
    },

    containerTextMobileInit: {
      ...containerTextMobile,
      height: "50vh",
    },

    containerTextMobileSteps: {
      ...containerTextMobile,
      height: "75vh",
      width: "100%",
    },

    containerTextDesktop: {
      ...containerText,
      height: "100vh",
      position: "relative",
      alignItems: "center",
    },

    textMobile: {
      ...text,
      height: "46vh",
      flexDirection: "column",
      display: "flex",
      justifyContent: "space-between",
    },

    textDesktop: {
      ...text,
      position: "absolute",
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },

    buttonContainerMobile: {
      ...buttonContainer,
      padding: 20,
    },

    buttonContainerDesktop: {
      ...buttonContainer,
    },

    button: {
      background: "-webkit-linear-gradient(40deg,#ffd86f,#fc6262)",
      color: "#fff",
      fontWeight: "bold",
    },

    // EFFECT

    textFocusInMobile: {
      ...textFocusIn,
    },

    textFocusInDesktop: {
      ...textFocusIn,
      position: "absolute",
      top: "40%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },

    slideInBottom: {
      "-webkit-animation":
        "$slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both",
      animation:
        "$slide-in-bottom 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both",
    },

    slideOutLeft: {
      "-webkit-animation":
        "$slide-out-left 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
      animation:
        "$slide-out-left 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
    },

    slideInRight: {
      height: "100vh",
      widht: "100vw",
      backgroundColor: "red",
      "-webkit-animation":
        "$slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
      animation:
        "$slide-in-right 0.5s cubic-bezier(0.550, 0.085, 0.680, 0.530) both",
    },

    hide: {
      display: "none",
    },

    /* ----------------------------------------------
     * Generated by Animista on 2021-9-15 17:55:43
     * Licensed under FreeBSD License.
     * See http://animista.net/license for more info.
     * w: http://animista.net, t: @cssanimista
     * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation textFocusIn
     * ----------------------------------------
     */
    "@-webkit-keyframes textFocusIn": {
      "0%": {
        "-webkit-filter": "blur(12px)",
        filter: "blur(12px)",
        opacity: 0,
      },
      "100%": {
        " -webkit-filter": "blur(0px)",
        filter: "blur(0px)",
        opacity: 1,
      },
    },
    "@keyframes textFocusIn": {
      "0%": {
        "-webkit-filter": "blur(12px)",
        filter: "blur(12px)",
        opacity: 0,
      },
      "100%": {
        "-webkit-filter": "blur(0px)",
        filter: "blur(0px)",
        opacity: 1,
      },
    },

    /**
     * ----------------------------------------
     * animation slide-in-bottom
     * ----------------------------------------
     */
    "@-webkit-keyframes slide-in-bottom": {
      "0%": {
        "-webkit-transform": "translateY(1000px)",
        transform: "translateY(1000px)",
        opacity: 0,
      },
      "100%": {
        "-webkit-transform": "translateY(0)",
        transform: "translateY(0)",
        opacity: 1,
      },
    },
    "@keyframes slide-in-bottom": {
      "0%": {
        "-webkit-transform": "translateY(1000px)",
        transform: "translateY(1000px)",
        opacity: 0,
      },
      "100%": {
        "-webkit-transform": "translateY(0)",
        transform: "translateY(0)",
        opacity: 1,
      },
    },

    /**
     * ----------------------------------------
     * animation slide-out-left
     * ----------------------------------------
     */
    "@-webkit-keyframes slide-out-left": {
      "0%": {
        "-webkit-transform": "translateX(0)",
        transform: "translateX(0)",
        opacity: 1,
      },
      "100%": {
        "-webkit-transform": "translateX(-1000px)",
        transform: "translateX(-1000px)",
        opacity: 0,
      },
    },
    "@keyframes slide-out-left": {
      "0%": {
        "-webkit-transform": "translateX(0)",
        transform: "translateX(0)",
        opacity: 1,
      },
      "100%": {
        "-webkit-transform": "translateX(-1000px)",
        transform: "translateX(-1000px)",
        opacity: 0,
      },
    },

    /**
     * ----------------------------------------
     * animation slide-in-right
     * ----------------------------------------
     */
    "@-webkit-keyframes slide-in-right": {
      "0%": {
        "-webkit-transform": "translateX(1000px)",
        transform: "translateX(1000px)",
        opacity: 0,
      },
      "100%": {
        "-webkit-transform": "translateX(0)",
        transform: "translateX(0)",
        opacity: 1,
      },
    },
    "@keyframes slide-in-right": {
      "0%": {
        "-webkit-transform": "translateX(1000px)",
        transform: "translateX(1000px)",
        opacity: 0,
      },
      "100%": {
        "-webkit-transform": "translateX(0)",
        transform: "translateX(0)",
        opacity: 1,
      },
    },
  };
});

export default useStyles;
